### PR TITLE
provide options for xmldom

### LINKED ISSUE #87: Provide options for xmldom constructor
The problem is then XML is broken we see these messages like `[xmldom error]	element parse error: Error: invalid tagName:` in the console.

If I want to throw an exception instead I would like to overload `errorHandler` in xmldom library.

### PR DESCRIPTION
**Pull request by unglud**
fixes #87

### CODE REVIEW

**Comment by unglud** [comment]
Merging is blocked, I don't know what I did wrong...

**Comment by Maxouhell** [comment]
Hi,
Please, do not reformat all the file, I can't see clearly what you updated.

Plus, if you can squash your commits into one, it will be better. 
And if you can, use the commitizen format (like : `feat(DomParser): provide options for xmldom`) i'll merge it as son as possible :)

**Comment by unglud** [comment]
We would like to start using this feature )

**Comment by Maxouhell** [comment]
Oh sorry ! I didn't see your updates.

I'll merge it !

**Pull request merged**
