### PR TITLE
feat: keepTextConfig

### PR DESCRIPTION
**Pull request by yzhe554**
This will enable user to always generate text node with __text.

### CODE REVIEW

**Comment by Maxouhell** [comment]
Thanks for your contribution !
I will deploy it soon in a new version ;)

**Comment by yzhe554** [comment]
Thanks. It will be great if you can release a new version soon.

**Comment by yzhe554** [comment]
@Maxouhell Hey Maxime, is that possible for you to do a release sooner? We need to use this feature.

**Comment by Maxouhell** [comment]
Oh sorry, I'll do this right now.

**Pull request merged**
