### PR TITLE
Fix typings export (refers to #57)

### PR DESCRIPTION
**Pull request by ezhukovskiy**
This pull request fixes import issues with the typings.

### CODE REVIEW

**Comment by cjonasw** [comment]
+1

**Comment by sandersaares** [comment]
I know almost nothing about TypeScript and typings but I see a thumbs up so I assume this is a sensible and good change and will merge it.

**Comment by akotynski** [comment]
This change breaks the backward compatibility.
Example below won't work any longer:
```typescript
import X2JS from 'x2js';
let x2js = new X2JS();
```
I got error `ERROR in ./src/app/file.ts (1,8): Module '"/opt/atlassian/pipelines/agent/build/node_modules/x2js/x2js"' has no default export.)`

**Comment by ezhukovskiy** [comment]
yes, it can break the backward compatibility, because the definition was wrong
it didn't reflect the real way the object is exported from js
can you use `import X2JS = require('x2js')` ?

**Comment by sam-s4s** [comment]
Sadly I can't use require coz it's not es6 compatible (and I use rollup).

**Comment by akotynski** [comment]
`import X2JS = require('x2js')` couse error: 
```
Import assignment cannot be used when targeting ECMAScript 2015 modules. Consider using 
'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', 
or another module format instead.)
```

`import * as X2JS from 'x2js';` works just fine.

**Pull request merged**
